### ISSUE TITLE
Failure to import tickets

### ISSUE THREAD

**Issue by pioto** [davglass/trac2issues#1]
I get this backtrace:

```
Traceback (most recent call last):
  File "/home/pioto/git/trac2issues/trac2issues.py", line 233, in <module>
    ImportTickets()
  File "/home/pioto/git/trac2issues/trac2issues.py", line 67, in __init__
    self._fetchTickets()
  File "/home/pioto/git/trac2issues/trac2issues.py", line 104, in _fetchTickets
    'milestone': milestone.replace(' ', '_'),
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by davglass** [comment]
Sorry, I didn't see this ticket. GH didn't email it to me :(

Let me take a look and see why that would fail. Do you have tickets without a milestone?

**Comment by davglass** [comment]
Just pushed a fix for this, I think it was an milestone with no name.

**Comment by pioto** [comment]
Yeah, I have many tickets w/o milestones.

However, the current fix doesn't seem to be sufficient:

```
Traceback (most recent call last):
  File "/home/pioto/git/trac2issues/trac2issues.py", line 240, in <module>
    ImportTickets()
  File "/home/pioto/git/trac2issues/trac2issues.py", line 67, in __init__
    self._fetchTickets()
  File "/home/pioto/git/trac2issues/trac2issues.py", line 112, in _fetchTickets
    'owner': owner.replace(' ', '_'),
AttributeError: 'NoneType' object has no attribute 'replace'
```

Guess we have a couple of different fields that're sometimes empty :p

(It's a rather oooold trac)

**Comment by davglass** [comment]
I added a check for no owner and no reporter as well..
