### ISSUE TITLE
urllib failure while importing tickets

### ISSUE THREAD

**Issue by johan** [davglass/trac2issues#2]
Importing the trac environment http://www.lysator.liu.se/~jhs/greasemonkey.trac.zip to an empty github issue tracker, aborts on this error:

> sudo ./trac2issues.py -p greasemonkey -m -x -o -r -c -u http://greasemonkey.devjavu.com -t /var/trac/greasemonkey
> Does this look like a valid trac url? [y/N]
>  http://greasemonkey.devjavu.com/ticket/1234567
> y
> About to import (260) tickets from Trac to johan/greasemonkey.
> Are you sure you wish to continue? [y/N]
> y
> Creating issue.
> Issue #1 created.
>         Adding label @ to issue # 1
>         Adding label @@reklam@nyh.se to issue # 1
> Traceback (most recent call last):
>   File "./trac2issues.py", line 250, in <module>
>     ImportTickets()
>   File "./trac2issues.py", line 67, in **init**
>     self._fetchTickets()
>   File "./trac2issues.py", line 141, in _fetchTickets
>     self.createIssue(data)
>   File "./trac2issues.py", line 179, in createIssue
>     self.createLabel(num, "@@%s" % info['reporter'])
>   File "./trac2issues.py", line 203, in createLabel
>     response = urllib2.urlopen(req)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 124, in urlopen
>     return _opener.open(url, data, timeout)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 389, in open
>     response = meth(req, response)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 502, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 427, in error
>     return self._call_chain(_args)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 361, in _call_chain
>     result = func(_args)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 510, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
> urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by johan** [comment]
Ugh. Pardon the shell session not surviving MarkDown interpretation unscathed.

**Comment by dkindlund** [comment]
Not sure if this is related, but according to:
http://develop.github.com/p/general.html

If you make more than 60 API calls per minute, the web service will actively block your connections (for a brief period of time).  This problem will occur if you have a significantly large number of tickets.  Adding sleep(5) calls between web service calls will prevent this from happening.
